In [7]:
import numpy as np

a = np.arange(15).reshape(3,5)


In [8]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
import numpy as np

def zeroMatrix(inputMatrix):
    aDims = inputMatrix.shape
    
    for row in range(aDims[0]) :
        for col in range(aDims[1]) :
            if inputMatrix[row][col] == 0:
                for icol in range(aDims[1]):
                    inputMatrix[row][icol] = 0
                for irow in range(aDims[0]):
                    inputMatrix[irow][col] = 0
                return   
                    
    print(inputMatrix)

In [18]:
b = np.arange(12).reshape(4,3)

In [19]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
zeroMatrix(b)

In [21]:
print(b)

[[ 0  0  0]
 [ 0  4  5]
 [ 0  7  8]
 [ 0 10 11]]
